# fly.toml app configuration file generated for test-logger on 2023-09-07T17:11:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "test-logger"
primary_region = "ord"

[build]
image = "ghcr.io/superfly/fly-log-shipper:latest"

[[services]]
http_checks = []
internal_port = 8686

[env]
QUEUE = "org-logs"
